# Textos en francés de seizeapps.com (/fr/). Mismas claves que UI['es'] y que el
# bloque castellano de cada app en gen_site.py; el castellano es el original.
# Tipografía francesa: U+00A0 antes de «:» y dentro de « », U+202F antes de ; ! ?
# (glosario: ~/dev/seize/docs/i18n/glosario-seize.md).

UI_FR = dict(
   nav_apps='Apps', nav_phil='Philosophie', nav_work='Travailler avec nous', nav_studio='Studio', nav_cta='Écris-nous',
   lang_switch='Français', lang_switch_aria='Lire en français', lang_name='Français',
   footer_tag='Des apps pour des lendemains meilleurs.', footer_privacy='Confidentialité', footer_terms='Conditions d’utilisation',
   copyright='© 2026 Seize Apps · Izotz Cristobal Mota &amp; Sendoa Sola · Pays basque, Espagne',
   site_title='Seize Apps — Des apps iOS extraordinaires pour le quotidien',
   site_desc='Seize conçoit et développe des apps iOS exceptionnelles qui rendent la vie meilleure : {apps}. Un studio indépendant du Pays basque qui réalise aussi des apps et des sites web pour des clients.',
   og_title='Seize — Des idées devenues extraordinaires.',
   hero_eyebrow='Des apps pour des lendemains meilleurs', hero_h1='Des idées devenues <span>extraordinaires.</span>',
   hero_lede='Nous concevons et développons des apps iOS exceptionnelles qui rendent la vie meilleure. Petites, natives et privées dès la conception : chacune fait une seule chose, et la fait bien. Et nous travaillons de la même façon pour les autres.',
   hero_cta='Voir les apps', hero_cta2='Travailler avec nous',
   apps_eyebrow='Apps', apps_h2='{Count} apps, <span>{count} tâches.</span>',
   apps_p='Le rythme de la maison, la journée de travail, l’argent qui part chaque mois, le rétablissement, les garanties, les comptes d’un couple, le bloc d’entraînement, les macros de ce que tu manges et les adresses qui valent le détour. Des problèmes différents, une seule façon de construire : un écran qui se comprend d’un coup d’œil, seulement les données nécessaires, et des textes en plusieurs langues, le français compris pour la plupart d’entre elles.',
   learn_more='En savoir plus',
   phil_eyebrow='Philosophie', phil_h2='Beau. Utile. <span>Humain. Possible.</span>',
   phil_p='Quatre mots à l’aune desquels nous jugeons chaque écran. Si une fonction échoue à l’un d’eux, elle ne sort pas, aussi ingénieuse soit-elle.',
   values=[('Beau','Un design avec un parti pris : une couleur dominante, le poids avant la taille, des animations qui veulent dire quelque chose. Ce soin qu’on remarque sans que personne ait besoin de le signaler.'),
           ('Utile','Chaque app répond à une vraie question que les gens se posent chaque jour, et y répond dès le premier écran. Pas de tableaux de bord pour le plaisir d’en avoir.'),
           ('Humain','Pas de mesure d’audience, pas de publicité, pas de pièges. Pas de compte non plus, sauf là où l’app est une communauté : Garum est la seule. Tout le reste vit sur ton iPhone et dans ton propre iCloud, et nous ne le voyons jamais. Des textes écrits pour des personnes, en plusieurs langues.'),
           ('Possible','Natif de bout en bout : SwiftUI, widgets, Activités en direct, Siri et Santé quand ils apportent quelque chose. Une petite équipe peut construire des apps qu’on croirait signées Apple.')],
   work_eyebrow='Travailler avec nous', work_h2='Le même savoir-faire, <span>pour ton projet.</span>',
   work_p='Nous acceptons quelques projets de clients par an : ceux qui nous permettent de travailler avec la même exigence que pour nos propres apps. Si tu as besoin de quelque chose de bien fait, parlons-en.',
   work_items=[('Apps iOS','Swift et SwiftUI natifs, du premier croquis à l’App Store : produit, design, code, relecture et la publication elle-même. Widgets, Activités en direct, Siri et iCloud quand ils apportent quelque chose.'),
               ('Sites et applications web','Des sites et des applications web rapides, accessibles et simples à maintenir : d’une page d’accueil comme celle-ci jusqu’à un produit complet.'),
               ('Développement sur mesure','Des outils, des intégrations et l’automatisation qui supprime une tâche que personne ne devrait faire à la main. Cadré, livré, documenté.')],
   work_how_title='Comment nous travaillons', work_how=[('Le cadre','Un document qui dit ce qui est livré, combien ça coûte et quand. Pas de surprise en cours de route.'),('Un seul responsable','L’un de nous deux porte ton projet du début à la fin, et c’est à lui que tu parles.'),('Les livraisons','Un logiciel qui fonctionne à chaque étape ; le code et la documentation sont à toi dès le premier jour.')],
   work_cta='Parle-nous de ton projet', work_subject='Demande de projet',
   studio_eyebrow='Studio', studio_h2='Deux développeurs, <span>une même exigence.</span>',
   studio_p='Seize Apps, c’est Izotz et Sendoa, deux cofondateurs du Pays basque. Chaque app, c’est nous deux : le même niveau d’exigence et le même soin, du premier croquis à la publication.',
   role='Cofondateur · Développeur', bio_izotz='Produit, design et code sur tout le catalogue.', bio_sendoa='Produit, design et code sur tout le catalogue.',
   studio_note='Nous publions nos propres apps et nous travaillons pour des clients, et nous restons assez petits pour que la personne qui a écrit le code soit celle qui lit ton e-mail.',
   contact_eyebrow='Contact', contact_h2='Écris-nous.', contact_p='Des questions, des idées, un projet, un bug que tu as repéré : une seule adresse, et nous lisons tout.',
   app_eyebrow='Seize Apps · iOS', shots_aria='Captures d’écran', what_eyebrow='Ce qu’elle fait', what_h2='Une seule chose, <span>bien faite.</span>',
   privacy_eyebrow='Confidentialité', privacy_h3='À toi, pas à nous.', published_by='Une app de Seize Apps.',
   privacy_policy='Politique de confidentialité', contact='Contact', store_badge='Télécharger dans l’App Store', store_icon='{name} dans l’App Store',
   shot_alt='Capture d’écran de {name} : {cap}',
   skip='Aller au contenu', lang_label='Langue', soon='Bientôt disponible', live_title='Sur l’App Store', more_apps='Aussi chez Seize', toc_title='Sur cette page',
   hero_proof='{n} apps · {live} sur l’App Store · Conçues au Pays basque',
)

APPS_FR = {
 'cycle-timers': dict(
   one='Des minuteurs récurrents pour la maison, lisibles d’un coup d’œil depuis le widget, sans ouvrir l’app.',
   tags=['Maison','Widgets','iOS'],
   lede='Chaque tâche de la maison a son cycle. <strong>Cycle Timers</strong> transforme ce que tu répètes et que tu oublies — l’eau des plantes, les draps propres, la litière du chat — en anneaux qui se vident avec le temps et repartent dès que tu marques la tâche comme faite.',
   meta=['iOS 17+','Widgets de l’écran d’accueil et de l’écran verrouillé','Sans compte'],
   features=[('01 / VOIR','Le temps, d’un coup d’œil','La couleur et la forme te disent ce qui est récent, ce qui approche et ce qui demande ton attention maintenant. Aucune liste à lire.'),
             ('02 / TOUCHER','Fait veut dire relancé','Un toucher marque la tâche comme faite et lance le cycle suivant, directement depuis le widget si tu veux.'),
             ('03 / GARDER','À toi, pas à nous','Sans compte et sans pistage. Tes minuteurs restent sur ton appareil, là où doit vivre un outil pour la maison.')],
   privacy='Cycle Timers n’a ni compte ni publicité. Les minuteurs vivent sur ton appareil, dans un conteneur privé partagé uniquement avec les widgets de l’app ; les rappels sont programmés en local. La seule chose qu’elle partage, c’est la mesure des achats (RevenueCat), jamais tes minuteurs.',
   captions=['Six anneaux, un coup d’œil','Un minuteur, c’est un nom, une icône et un cycle']),
 'tempo': dict(
   one='Un compagnon de journée qui retient tes heures à ta place — arriver, travailler, partir — et te laisse la main sur le relevé pour le corriger.',
   tags=['Travail','Heures','Calendrier'],
   lede='Ta journée se mesure à ce que tu accomplis, pas aux heures que tu surveilles. <strong>Tempo</strong> remarque quand tu arrives au travail et quand tu pars, additionne le tout en une journée honnête et te laisse vérifier, découper ou corriger n’importe quel moment. Mode manuel dès le premier jour ; suivi automatique seulement si tu choisis de dessiner une zone de travail.',
   meta=['iOS 17+','Activités en direct','Export vers Calendrier','Sans compte'],
   features=[('01 / ARRIVER','Des heures sans rien toucher','Dessine une zone de travail une fois et Tempo fait le reste avec la localisation qu’iOS garde déjà. Plusieurs passages s’additionnent en une journée exacte.'),
             ('02 / VOIR','Aujourd’hui, clairement','Le temps travaillé, ton objectif du jour, l’arrivée et le départ sur un seul écran, et une vue du mois qui montre d’un coup d’œil les jours dans les temps, les jours courts et ceux avec des heures en plus.'),
             ('03 / À TOI','Ton relevé, modifiable','Vérifie, corrige, découpe, fusionne ou exporte. Si une limite n’était pas claire, Tempo te pose la question au lieu de deviner.')],
   privacy='Tempo garde tes sessions, tes zones et tes objectifs sur ton appareil. La localisation sert uniquement à détecter la zone de travail que tu as dessinée, sur le téléphone lui-même, et n’est jamais envoyée nulle part. Sans compte ni publicité ; la seule chose qu’elle partage, c’est la mesure des achats (RevenueCat), jamais ton travail ni ta localisation.',
   captions=['Ta journée, retenue pour toi','Aujourd’hui : le temps travaillé face à ton objectif','Un mois de journées, colorées selon leur déroulement']),
 'drip': dict(
   one='Vois exactement où file ton argent : chaque abonnement, facture et cotisation, avec ce qu’il coûte vraiment à l’année.',
   tags=['Abonnements','Budget','FR · EN · ES'],
   lede='Payer au mois cache la douleur. <strong>Drip</strong> suit chaque service récurrent — abonnements, factures, cotisations — et met le vrai coût annuel à côté de ce que tu paies chaque mois. Gratuite au quotidien ; Drip Pro est un achat unique, avec un essai gratuit de 30 jours. Sans compte, sans publicité, sans abonnement : juste le chiffre, et ce que tu en fais.',
   meta=['iOS 17+','Gratuit · Pro, achat unique','Widgets et Siri (Pro)','Français · Anglais · Espagnol'],
   features=[('01 / VOIR','Le coût annuel, toujours','Ces « seulement 9,99 € par mois », c’est 120 € par an. Drip affiche les deux, pour chaque service, en permanence, avec le total par mois, par trimestre et par année. Drip Pro ajoute l’analyse poussée : la tendance sur douze mois, les variations saisonnières et la répartition par catégorie, les tiennes comprises.'),
             ('02 / MAÎTRISER','Savoir ce qui arrive','Les prélèvements des 14 prochains jours d’un coup d’œil, des alertes de fin d’essai et un balayage pour marquer un prélèvement comme payé. Mets un service en pause au lieu de le supprimer. Avec Drip Pro, un budget mensuel et le récap annuel de ce que tu as dépensé.'),
             ('03 / GARDER','À toi, pas à nous','Sans compte et sans pistage. Tes services vivent sur ton appareil et dans ton propre iCloud, jamais sur un serveur à nous.')],
   privacy='Drip enregistre tes services sur ton appareil, dans un conteneur privé partagé uniquement avec ses widgets et ses raccourcis Siri, et dans ton propre compte iCloud ; jamais à un endroit que nous pourrions voir.',
   captions=['Tableau de bord : le chiffre annuel d’abord','Chaque service, au mois et à l’année','Là où ça file le plus, et par catégorie','Le récap annuel (Pro)']),
 'anchor': dict(
   one='Un soutien au quotidien pour se rétablir d’un trouble des conduites alimentaires : des routines qui te portent et des outils pour le moment difficile, aux côtés d’une prise en charge professionnelle, jamais à sa place.',
   tags=['Rétablissement','Routines','FR · EN · ES'],
   lede='<strong>Anchor</strong> accompagne les personnes qui se rétablissent d’un trouble des conduites alimentaires. Des routines qui te portent — repas, repos, mouvement — confirmées d’un toucher ; une seule porte, <em>Maintenant</em>, pour le moment difficile : surfer sur l’envie, respirer avec un guide, laisser passer une émotion ou ouvrir ton plan de sécurité. Pas de calories, pas de poids, pas de jours d’affilée à tenir. Jamais.',
   meta=['iOS 17+','Gratuit','Activités en direct','Santé (facultatif, lecture seule)','Français · Anglais · Espagnol'],
   features=[('01 / TENIR','Des routines, pas des règles','Repas, repos et mouvement en blocs de la journée. Confirme d’un toucher ; si une journée ne se passe pas comme prévu, ce n’est pas grave, et Anchor te le dit.'),
             ('02 / MAINTENANT','Une porte pour le moment difficile','Surfer sur l’envie avec quinze minutes d’accompagnement, une respiration guidée sans retenir ton souffle, « La laisser passer » pour une émotion forte, et un plan de sécurité avec tes proches et les lignes d’écoute de ta région, à deux touchers.'),
             ('03 / VOIR','Sans chiffres','Un point du jour sur tes émotions sans score, des stratégies issues de la TCD, de la TCC, de l’ACT et de l’autocompassion avec leurs fondements bien visibles, et tes progrès montrés comme la forme de ta semaine, pas comme une note.')],
   privacy='Tout ce que tu saisis reste sur ton appareil et dans ton propre iCloud privé. L’accès à Santé est facultatif et en lecture seule (sommeil, activité), jamais le poids ni la nutrition, et ces données ne quittent jamais le téléphone. Pas de mesure d’audience, pas de publicité, pas de conversation avec une IA.',
   captions=['Accueil : la prochaine routine, et « Maintenant »','« Qu’est-ce qui se passe ? » mène au bon outil','Un point du jour sans chiffres','Des stratégies, avec leurs fondements'],
   extra='Anchor n’est pas un dispositif médical et ne remplace pas une prise en charge professionnelle. Si tu es en danger ou si tes propres pensées te font peur, appelle le numéro d’urgence de ta région.'),
 'kover': dict(
   one='Prends le ticket en photo et Kover veille sur la garantie : ce qui est couvert, jusqu’à quand, et un rappel avant qu’elle se termine.',
   tags=['Garanties','Tickets','FR · EN · ES'],
   lede='Les tickets s’effacent, les garanties expirent sans prévenir. <strong>Kover</strong> lit la date, le magasin et le montant sur une photo ou un PDF du ticket, calcule la garantie légale de ton pays et range la photo, le numéro de série et le contact du SAV au même endroit, avec un rappel un mois avant, une semaine avant et le jour même de la fin.',
   meta=['iOS 17+','Gratuit · Pro, achat unique','Appareil photo, Photos ou PDF','Français · Anglais · Espagnol'],
   features=[('01 / AJOUTER','Trois questions, puis le sceau','Ce que tu as acheté, quand et où, combien. Ou laisse le ticket répondre : appareil photo, Photothèque ou un PDF reçu par e-mail, et les étapes arrivent pré-remplies. L’enregistrement se termine sur « Couvert jusqu’au ».'),
             ('02 / VEILLER','Couvert jusqu’au…, en toutes lettres','La garantie légale selon le pays — 36 mois en Espagne — plus l’extension de garantie s’il y en a une. « Encore 3 ans », pas un compte à rebours en jours, sur un sceau qui s’use avec le temps. Des rappels un mois avant, une semaine avant et le jour même.'),
             ('03 / RÉCLAMER','Tout pour le jour où tu en as besoin','Numéro de série, téléphone ou site du SAV à un toucher, et la photo du ticket. Réclamé, remplacé ou plus à toi : archive au lieu de supprimer. Kover Pro ajoute plus de documents par produit, un PDF de réclamation, l’export CSV et Siri : un achat unique, avec un essai gratuit de 30 jours.')],
   privacy='Kover garde tes produits et les photos de tes tickets sur ton appareil et dans ton propre compte iCloud. Les tickets sont lus sur le téléphone avec le framework Vision d’Apple : rien n’est envoyé, sans compte, sans mesure d’audience.',
   captions=['La prochaine à expirer, et toute l’étagère','Trois questions : quoi, quand, combien — ou le ticket','Couvert jusqu’en 2029, sur son sceau','Des rappels avant la fin']),
 'tandem': dict(
   one='Le partage équitable des dépenses à deux : chacun paie en proportion de ce qu’il gagne, et le mois se boucle en un seul chiffre.',
   tags=['Couple','Dépenses','FR · EN · ES'],
   lede='Moitié-moitié n’est juste que si vous gagnez la même chose. <strong>Tandem</strong> prend les deux revenus et chaque dépense commune — le loyer, les courses, le dîner au restaurant — et la répartit en proportion, pour que le mois se termine par un seul virement que vous comprenez tous les deux. Un seul téléphone tient les comptes du couple.',
   meta=['iOS 17+','Gratuit · Pro, achat unique','Widgets (Pro)','Français · Anglais · Espagnol'],
   features=[('01 / RÉPARTIR','Proportionnel par défaut','Saisis les deux revenus une fois. Chaque dépense est répartie selon cette proportion — ou à 50/50, ou payée en entier par l’un de vous, ou, avec Tandem Pro, selon la part dont vous convenez — et la proportion est figée avec la dépense : une augmentation l’an prochain ne rouvre jamais les mois de l’année d’avant.'),
             ('02 / RÉGLER','Un chiffre par mois','Qui a payé quoi, qui doit quoi à qui, et le virement qui remet tout d’équerre. Marque le mois comme réglé. Trop rapide ? Tu peux annuler.'),
             ('03 / VOIR','Où part l’argent','Des dépenses récurrentes qui se notent toutes seules. Tandem Pro ajoute des rapports par catégorie et par mois, des rappels pour noter et pour régler, et des widgets : un achat unique, avec un essai gratuit de 30 jours.')],
   privacy='Tandem garde les noms, les revenus et les dépenses sur ton appareil et dans ton propre compte iCloud. Rien n’est partagé avec personne : ni avec nous, ni avec un serveur.',
   captions=['Ce mois-ci : commun, payé, à régler','Fixes et variables, par mois','Régler les comptes : le calcul, sous les yeux','Rapports : qui a payé, mois par mois (Pro)']),
 'meso': dict(
   one='Le tableur de ton coach, version salle de sport : des blocs de semaines, la charge et les reps de chaque série, l’effort en répétitions en réserve.',
   tags=['Force','Blocs et RIR','FR · EN · ES'],
   lede='Un programme est un bloc de semaines, pas une liste de séances. <strong>Meso</strong> prend les séances que ton coach a écrites — ou l’un de ses modèles — et les transforme en un journal qui se remplit tout seul : chaque série arrive pré-remplie avec ta meilleure séance récente, les séries restantes suivent chaque série que tu valides, un toucher suffit pour valider, et l’effort se note en répétitions en réserve. Ensuite, Meso te montre si le bloc avance : le tonnage par exercice semaine après semaine et, avec Meso Pro, les séries par muscle face à ce que la recherche juge suffisant.',
   meta=['iOS 17+','Gratuit · Pro, achat unique','Santé (Pro)','Français · Anglais · Espagnol'],
   features=[('01 / NOTER','Un toucher par série','Charge, reps et RIR arrivent pré-remplis depuis ta meilleure séance récente, et chaque série validée réajuste les suivantes à leurs propres reps et RIR ; quand rien n’a changé, la coche suffit. Une note par exercice, des séries d’échauffement si tu en veux, et la série suivante sur l’écran verrouillé.'),
             ('02 / PROGRESSER','Des blocs, pas des jours','Une grille du tonnage par exercice au fil des semaines. Meso Pro ajoute les séries par muscle face à la bande 10–20, le 1RM estimé de chaque exercice d’un bloc à l’autre, l’étape suivante avant ta première série, et tes salles avec leur barre et leurs disques : un achat unique, avec un essai gratuit de 30 jours. Pas de jours d’affilée, pas de confettis : la progression se mesure en blocs.'),
             ('03 / APPRENDRE','Chaque règle avec sa source','Pourquoi le RIR, pourquoi une décharge, pourquoi la bande : chaque principe de l’app vient avec ses preuves et leur solidité, et des références que tu peux vérifier. Honnête sur ce qui est établi et sur ce qui ne l’est pas.')],
   privacy='Meso garde tes programmes et tes séances sur ton appareil et dans ton propre compte iCloud. Meso n’écrit dans Santé que si tu l’actives, et n’y lit jamais rien. Sans compte, sans mesure d’audience.',
   captions=['Aujourd’hui : la séance prévue','Une série, c’est une coche ; le reste est pré-rempli','Le tonnage par exercice, semaine après semaine','Les séries par muscle face à la bande fondée sur les preuves (Pro)']),
 'grain': dict(
   one='Un journal de macros sans discours de régime : énergie, protéines, glucides et lipides face aux objectifs que tu fixes, et ce qu’il reste.',
   tags=['Nutrition','Macros','FR · EN · ES'],
   lede='Prendre du muscle, perdre du gras ou suivre ce que ta diététicienne ou ton diététicien t’a prescrit : <strong>Grain</strong> sert à tout cela de la même façon. Les objectifs, c’est toi qui les fixes ; Grain note ce que tu manges et compare, sans proposer ni juger. Dépasser ne s’affiche pas en rouge, atteindre l’objectif ne s’affiche pas en vert : la barre se remplit dans sa couleur et le chiffre indique « +12 g ». Plus de 4 000 aliments des tables CIQUAL et BEDCA sont inclus dans l’app et fonctionnent hors connexion.',
   meta=['iOS 26+','Gratuit · Pro, achat unique','Santé (Pro)','Français · Anglais · Espagnol'],
   features=[('01 / NOTER','Comme tu le dirais','Écris « 2 œufs, 60 g de pain grillé, 10 g d’huile d’olive » et Grain sépare les aliments et propose les grammes, avec les valeurs des tables ; tu vérifies avant que ce soit noté. Ou cherche, scanne un code-barres (Open Food Facts), crée une recette et note-la à son poids une fois cuite, ou saisis les macros à la main. Les portions habituelles sont déjà réglées, et tout aliment qui ne correspond pas à son emballage peut être corrigé.'),
             ('02 / LIRE','L’étiquette, sur ton iPhone','Avec Grain Pro, pointe l’appareil photo vers le tableau nutritionnel, ou choisis une photo, et les valeurs pour 100 g se remplissent toutes seules. La lecture se fait sur l’appareil ; rien ne quitte le téléphone.'),
             ('03 / REVOIR','Ce que donnent tes semaines','Chaque repas affiche son total à côté de son nom, et la journée montre ce qu’il reste d’énergie et de chaque macro. Grain Pro ajoute l’historique sur sept, trente ou quatre-vingt-dix jours, avec la moyenne des seuls jours notés (et il le dit), plus les widgets et Santé : un achat unique, avec un essai gratuit de 30 jours. Pas de jours d’affilée, pas de poids.')],
   privacy='Grain garde ton journal sur ton appareil et dans ton propre compte iCloud. D’un code-barres, seul le numéro part, vers Open Food Facts, sauf si tu choisis de lui envoyer un produit. Grain n’écrit dans Santé que si tu l’actives, et n’y lit jamais rien. Sans compte, sans mesure d’audience.',
   captions=['Aujourd’hui : ce que tu as mangé face à tes objectifs, et ce qu’il reste','Écris un repas comme tu le dirais','Une étiquette nutritionnelle, lue sur l’iPhone (Pro)','Ce que donnent les semaines, par macro (Pro)']),
 'garum': dict(
   one='Une carte d’adresses qui ont une raison d’être là : des classiques, des établis et des nouveaux qui ont un parti pris, chacun avec son pourquoi, et tout est signé.',
   tags=['Manger et boire','Carte sélective','FR · EN · ES'],
   lede='<strong>Garum</strong> est une carte où les adresses entrent au mérite, pas grâce aux étoiles ni à la publicité. Trois listes selon l’ancienneté — les classiques, ouverts depuis plus de 25 ans, les établis, entre 3 et 25 ans, et les nouveaux, de moins de 3 ans, qui ont un parti pris — et les adresses passent d’une liste à la suivante toutes seules, avec les années. Chacune porte les raisons de sa présence et des notes signées par qui s’en porte garant. Tout le monde peut proposer une adresse ; elle entre quand un Curator la signe ou que suffisamment de personnes de confiance la recommandent.',
   meta=['iOS 26+','Gratuit','Plans','Français · Anglais · Espagnol'],
   features=[('01 / POURQUOI','Chaque adresse, avec son pourquoi','Une liste fermée de motifs — un classique, le produit, le prix, le lieu — et des notes signées, jamais de notation. Horaires, téléphone et itinéraire arrivent en direct depuis Plans.'),
             ('02 / TROUVER','Ce qui te fait envie, maintenant','Filtre par liste, type d’adresse, cuisine, prix et moment, ou selon ce qui convient en ce moment même. Quoi commander et s’il faut réserver : c’est sur la fiche.'),
             ('03 / SIGNÉ','Tout est signé','Vois qui recommande chaque adresse et suis des gens qui ont tes goûts. Propose ce qui manque ; si ça n’entre pas, on te dit pourquoi. Les Curators peuvent aussi proposer de retirer une adresse qui a fermé ou qui n’est plus ce qu’elle était, et la modération décide, motif à l’appui.')],
   privacy='Regarder la carte ne demande aucun compte. Pour voir pourquoi chaque adresse est là et pour contribuer, tu te connectes avec Apple, sans donner ton e-mail : tu apparais avec le nom que tu partages avec Apple (ou celui que tu choisis ensuite) et un nom d’utilisateur, et ce que tu apportes est publié, sur un serveur situé dans l’UE. Pas de publicité, pas de mesure d’audience. Garum a sa propre politique de confidentialité et ses propres conditions d’utilisation.',
   captions=['La carte : classiques, établis et nouveaux','Chaque adresse avec ses motifs et des notes signées','Quoi commander, quand y aller, s’il faut réserver','Tout est signé : qui recommande quoi']),
 'sacapuntas': dict(
   one='Des cahiers d’exercices pour toute l’école primaire, de 6 à 12 ans, en espagnol et en basque : calcul, tables de multiplication, accents, grammaire et compréhension écrite, avec un village qui grandit à chaque page bien terminée.',
   tags=['Éducation','Primaire','ES · EU'],
   lede='Les cahiers d’exercices que tous les enfants connaissent en Espagne, en version numérique et avec humour. <strong>Sacapuntas</strong> (« taille-crayon ») couvre les opérations posées avec retenues, la multiplication à deux chiffres et la division posée à l’espagnole, le calcul mental et les tables, la numération, les syllabes et l’accentuation espagnole selon les règles de la RAE, la grammaire et la compréhension écrite. Chaque enfant travaille dans sa langue : il y a aussi un parcours en basque. Des pages courtes avec une fin claire ; chaque page bien terminée rapporte des copeaux pour construire son propre village. L’app suit l’école espagnole, en espagnol et en basque.',
   meta=['iOS 26+','iPhone et iPad','Gratuit · Pro, à vie ou par abonnement','Espagnol · Basque'],
   features=[('01 / OPÉRATIONS','Chiffre par chiffre','Chaque chiffre dans sa case et chaque retenue à sa place. Une erreur marque la case et l’indice dit quelle colonne regarder ; si la même erreur revient, elle est reconnue et expliquée. Une opération juste n’est jamais comptée fausse parce qu’elle suit une autre méthode.'),
             ('02 / ACCENTS','Agudas, llanas, esdrújulas','La syllabe accentuée, les trois catégories et « faut-il un accent ? », selon l’orthographe de la RAE de 2010, avec de vrais mots du niveau de l’enfant.'),
             ('03 / FAMILLES','Derrière le code famille','Des profils, le bilan de la semaine avec ce qui coince et une activité à faire ensemble, l’année scolaire et ce qui a été vu en classe, les méthodes de son école, des fiches à imprimer avec leurs corrigés, et Sacapuntas Pro : une fois pour toutes ou par abonnement, avec un essai gratuit qui se termine tout seul. L’enfant ne voit jamais un prix.')],
   privacy='Sacapuntas ne collecte aucune donnée sur l’enfant : sans compte, sans publicité, sans mesure d’audience et sans notifications. La progression reste sur l’appareil et, si la famille laisse l’option activée, dans son propre iCloud.',
   captions=['L’étagère : ce qu’il y a à faire','Additions posées, chiffre par chiffre','Le village construit avec des copeaux','Pour la famille : le bilan de la semaine']),

 'gaminghub': dict(
   one='Des jeux de soirée, chacun sur son téléphone : crée un salon, partage le code et jouez. Chaque appareil n’affiche que ce que tu as le droit de voir.',
   tags=['Jeux','Multijoueur','EN · ES'],
   lede='Transforme n’importe quelle soirée en soirée jeux. Avec <strong>GamingHub</strong>, tu crées un salon, tu partages le code ou le QR et chaque ami le rejoint depuis son propre téléphone. Chaque appareil n’affiche que ce que tu dois voir : ton rôle, ton mot, tes cartes. Impostor dans un bal masqué, Vault, Unison, Rewind, Spot On et Fishbowl sont des jeux originaux fondés sur des mécaniques classiques, joués en direct dans le salon.',
   meta=['iOS 17+','iPhone','Unison gratuit · le reste, achats uniques','Anglais · Espagnol'],
   features=[('01 / SALON','Un code, une table','Crée un salon, partage un code de quatre lettres ou un QR et tes amis apparaissent dans le salon d’attente à mesure qu’ils arrivent. Reprends ta table après un appel, un verrouillage d’écran ou un redémarrage.'),
             ('02 / SECRET','Chaque téléphone garde son secret','Ton rôle, ton mot et tes cartes ne sont envoyés qu’à ton appareil. Le salon voit la partie ; personne ne voit ta main.'),
             ('03 / JOUER','Gratuit pour essayer, à toi pour toujours','Unison est gratuit pour tout le monde. Les autres jeux sont des achats uniques, et toute ta table joue gratuitement dès que l’hôte possède le jeu ; sinon, chaque joueur a trois parties gratuites de chaque jeu. Les achats sont partagés avec ta famille.')],
   privacy='GamingHub n’a ni compte, ni e-mail, ni mot de passe. Pour faire tourner un salon, elle envoie à notre serveur (Supabase) un nom d’affichage que tu choisis, un avatar, un identifiant anonyme et l’état de la partie, que les autres joueurs du salon voient ; les salons sont supprimés quand ils se vident et purgés au bout de 12 heures. Sans publicité, sans mesure d’audience, sans suivi.',
   captions=['Accueil : crée un salon, rejoins-en un avec un code ou scanne un QR','Impostor : brise le sceau pour lire ton invitation','Unison : jouez vos cartes dans l’ordre, en silence']),
 'atino': dict(
   one='Importe ton CV et vois les offres d’emploi d’Europe classées selon leur correspondance, chacune avec un motif bref. Ton nom et tes coordonnées sont d’abord retirés sur ton iPhone.',
   tags=['Emploi','Europe','CV'],
   lede='<strong>Atino</strong> lit ton CV sur ton iPhone, retire ton nom et tes coordonnées et, avec ta permission, demande à un modèle d’IA de noter chaque offre à partir de ce qui reste. Plus de 100 000 offres en cours, issues de pages carrières d’entreprises et de données ouvertes de l’emploi, sont livrées avec l’app et mises à jour chaque jour. Chaque résultat affiche un pourcentage de correspondance et un motif bref ; le pourcentage est une estimation, pas une promesse, et le bouton pour postuler t’emmène sur la page de l’employeur.',
   meta=['iOS 26+','iPhone','Gratuit · Pro, abonnement','24 langues'],
   features=[('01 / IMPORTER','Ton CV reste à toi','Importe un PDF ; les scans fonctionnent aussi. Atino retire sur le téléphone ton nom, ton e-mail, ton téléphone, ton adresse, ta date de naissance et ton numéro d’identité, puis te montre le texte exact qu’il enverrait. Tu peux le modifier, et rien n’est envoyé tant que tu ne l’autorises pas.'),
             ('02 / CLASSER','La meilleure correspondance d’abord','Choisis où et comment tu veux travailler, puis lance la recherche. Les offres reviennent classées, chacune avec son pourcentage et le détail du travail, des compétences, du niveau et des exigences. Une recherche par jour et tes 10 meilleurs résultats sont gratuits.'),
             ('03 / SURVEILLER','Pro continue de chercher pour toi','Atino Pro ajoute tous les résultats, tous les filtres, les recherches enregistrées et autant de recherches que nécessaire dans la limite d’un usage raisonnable, plus une alerte par jour, à l’heure que tu choisis, quand une recherche enregistrée a du nouveau.')],
   privacy='Ton CV, tes résultats et tes recherches enregistrées restent sur ton iPhone. Avec ta permission, le texte expurgé du CV passe par le relais de Seize jusqu’à Command Code et TypeSafe AI (Jev) pour classer les offres ; ils peuvent le conserver selon leurs propres conditions. Sans compte, sans publicité, sans suivi ; ton abonnement est signalé à RevenueCat pour la mesure des achats. Atino a sa propre politique de confidentialité.',
   captions=['Résultats : les offres en cours classées par correspondance','Une offre : pourquoi elle correspond, et où postuler','Filtres : où et comment tu veux travailler']),

 'roomy': dict(
   one='Glisse à gauche pour supprimer, à droite pour garder. Roomy trouve aussi les doublons, les photos similaires et les vidéos énormes, le tout sur ton iPhone.',
   tags=['Utilitaires','Photos','9 langues'],
   lede='Une pellicule pleine est une corvée, jusqu’à ce qu’elle devienne un jeu. <strong>Roomy</strong> te montre tes photos une à une : à gauche pour supprimer, à droite pour garder, chaque geste peut être annulé et rien n’est supprimé tant que tu ne confirmes pas dans la corbeille. Le nettoyage intelligent trouve les doublons exacts, les rafales et les photos quasi identiques (avec la meilleure déjà marquée), les captures d’écran et les grosses vidéos qui remplissent vraiment le stockage, que Roomy peut compresser en gardant la date et le lieu.',
   meta=['iOS 17+','iPhone','Gratuit · Pro, abonnement ou à vie','9 langues'],
   features=[('01 / GLISSER','Un mois nettoyé en quelques minutes','Parcours ta photothèque mois par mois, par souvenirs « Ce jour-là » ou au hasard. Chaque geste peut être annulé et ce qui est supprimé attend dans la corbeille jusqu’à ta confirmation. Gratuit : 50 gestes par jour.'),
             ('02 / TROUVER','Le fouillis, trouvé pour toi','Doublons, photos similaires, captures d’écran et grosses vidéos ont chacun leur file. Les photos similaires arrivent groupées avec la meilleure marquée, et ce que tu as gardé n’est jamais présélectionné pour suppression.'),
             ('03 / LIBÉRER','Vois ce que tu as récupéré','Roomy Pro ajoute des gestes illimités, la suppression des doublons et des similaires en un geste et la compression vidéo, qui économise jusqu’à 80 % de place. Suis l’espace libéré et garde une série quotidienne.')],
   privacy='Roomy analyse ta photothèque uniquement sur ton iPhone. Tes photos, tes vidéos et leurs métadonnées ne sont jamais envoyées. Sans compte, sans mesure d’audience, sans publicité, sans suivi : rien ne quitte le téléphone. Les achats passent par Apple.',
   captions=['Accueil : l’espace libre et le fouillis trouvé par Roomy','À gauche pour supprimer, à droite pour garder','Photos similaires groupées, la meilleure marquée']),
}
